// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7023vWRXKblBOIwN709rbDMrHxyP8BDg',
    appId: '1:440035217980:web:ba075c75461256ea73e939',
    messagingSenderId: '440035217980',
    projectId: 'tradingpro-6c1ac',
    authDomain: 'tradingpro-6c1ac.firebaseapp.com',
    storageBucket: 'tradingpro-6c1ac.firebasestorage.app',
    measurementId: 'G-40V8KRW8EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3kMB972EJ2s0NsilDSPq_MhYh2JqeEk',
    appId: '1:440035217980:android:5095d06085cd6fde73e939',
    messagingSenderId: '440035217980',
    projectId: 'tradingpro-6c1ac',
    storageBucket: 'tradingpro-6c1ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtGWRc34OuizTOLFtJkiSQqqKu5Y4NFLk',
    appId: '1:440035217980:ios:0ee3898df9972d3573e939',
    messagingSenderId: '440035217980',
    projectId: 'tradingpro-6c1ac',
    storageBucket: 'tradingpro-6c1ac.firebasestorage.app',
    iosBundleId: 'com.tradingpro.it.tradingpro',
  );
}
